const types = {
   TOGGLE_FORM: 'TOGGLE_FORM',
   OPEN_FORM: 'OPEN_FORM',
   CLOSE_FORM: 'CLOSE_FORM',
   ADD_TASK: 'ADD_TASK',
   UPDATE_STATUS: 'UPDATE_STATUS',
   DELETE_TASK: 'DELETE_TASK',
   EDIT_TASK: 'EDIT_TASK',
   SAVE_TASK: 'SAVE_TASK',
   FILTER_TASK: 'FILTER_TASK',
   SEARCH_TASK: 'SEARCH_TASK',
   SORT_TASK: 'SORT_TASK'
}

export default types
